[build]
  base      = "/"
  publish   = "dist"
  command   = "npm run build"

[build.environment]
  NODE_VERSION = "10"
  NPM_VERSION = "6.4.1"

[[redirects]]
  from = "/hacktoberfest"
  to = "/?tags=hacktoberfest"

[[redirects]]
  from = "/rss"
  to = "/assets/feed/rss.xml"
[[redirects]]
  from = "/atom"
  to = "/assets/feed/atom.xml"
[[redirects]]
  from = "/json"
  to = "/assets/feed/feed.json"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Strict-Transport-Security = "max-age=15552000; preload"
    X-Content-Type-Options = "nosniff"

[[headers]]
    for = "/assets/swag-img/*"
    [headers.values]
    Cache-Control = 'public max-age=63072000' # 2 years cache for all assets since they're cachebusted

[[headers]]
    for = "/assets/js/*"
    [headers.values]
    Cache-Control = 'public max-age=63072000' # 2 years cache for all assets since they're cachebusted

[[headers]]
    for = "/assets/css/*"
    [headers.values]
    Cache-Control = 'public max-age=63072000' # 2 years cache for all assets since they're cachebusted

[[headers]]
    for = "/assets/feed/*"
    [headers.values]
    Cache-Control = 'public max-age=43200' # 12 hours for feeds
