[build]
  base      = "site/"
  publish   = "site/dist"
  command   = "gulp build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Strict-Transport-Security = "max-age=15552000; preload"
    X-Content-Type-Options = "nosniff"
